#title in header
title: "hi, i'm spencer"

#main info
#owner
email: spencer@spencergb.me
header: 
  - "thanks for stopping by!"
  - "here's a bit about me:"
desc: 
  - "I am a recent graduate from Columbia University, where I recieved a B.S. in Computer Science on the Vision, Graphics, Interaction, & Robotics track."
  - "While a student, I had loads of fun exploring the creative process and diversified my courseload with sociology, sustainability, and manufacturing courses. Outside of the classroom, I filled my time mentoring students in my job as a TA, tinkering in our Makerspaces, and trying new sweets around the Big Apple."
  - "My interests bring me too many niche topics to count, but some of my current favorites include: sustainability, crafting, baking, Thai food, reading, and running."
subdesc: "Here on my website you can find a few of my featured projects. Please have a look around and drop me a line if you'd like to collaborate!"

# siema carousel of images, options:
# ref: https://pawelgrzybek.github.io/siema/ (codepens are helpful too https://codepen.io/collection/Adpkkd/)
coverimages:
  - image: /images/headshot.jpg
    image_alt: "A photo of Spencer in front of Columbia University's Low Library. He is smiling, wearing a white collared shirt underneath a black sweater. On top of this he wears an unzipped light blue graduation gown. In the background you can see trees and the top of Riverside Church."
    description: I'm a python developer
  - image: /images/1.jpg
    image_alt: "Blueberry favicon"
    description: "Placeholder 1"
  - image: /images/2.jpg
    image_alt: "Blueberry favicon"
    description: "Placeholder 2"
  - image: /images/3.jpg
    image_alt: "Blueberry favicon"
    description: "Placeholder 3"
  - image: /images/4.jpg
    image_alt: "Blueberry favicon"
    description: "Placeholder 4"
  - image: /images/5.jpg
    image_alt: "Blueberry favicon"
    description: "Placeholder 5"
  - image: /images/6.jpg
    image_alt: "Blueberry favicon"
    description: "Placeholder 6"
  - image: /images/7.jpg
    image_alt: "Blueberry favicon"
    description: "this is the new image"

carousel:
  selector: '.siema'
  duration: 1000 # Slide transition duration in milliseconds
  easing: 'ease-in-out'
  perPage: 1 # The number of slides to be shown
  startIndex: 0
  draggable: true
  multipleDrag: true
  threshold: 20
  loop: true
  timer: 4000 # amount of time between autoscrolling images in ms, 0 = none

# for supplying a thumnail photo for each post
post_asset_folder: true 

# links to put on the links page
links: 
  - link: https://www.youtube.com/watch?v=_W44NZvHc9I
    text: Wow 1 
    color: 44444
  - link: https://www.youtube.com/watch?v=_W44NZvHc9I
    text: Wow 2 
    color: 6ab1c4

#menu
# menu:
#   Works: /works
#   About: /about

# Colors use hex color without #
# Theme color
tcolor: 6ab1c4

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/custom.css

# social profile at the footer/bottom
footer: true
placename: NYC
placelink: https://www.youtube.com/watch?v=_W44NZvHc9I
github: https://github.com/spencerbruce
linkedin: https://linkedin.com/in/spencergbruce
twitter: https://twitter.com/spencergbruce
instagram: https://instagram.com/spencergbruce
youtube: # https://www.youtube.com/user/SpencerBrucee
tiktok: # https://www.tiktok.com/@spun.cer

# Misc
nanobar: /js/nanobar.min.js
siema: /js/siema.min.js

switch_light: 🌃
switch_dark: 🌇

# favicon
favicon: /images/favicon.png
# thumbnail
# thumbnail: /images/thumbnail.jpg

# article:
#   thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
# disqus_enabled: false
# disqus_shortname: 
